<a href="https://colab.research.google.com/github/gauritiwari08-sudo/Data-Analyst-Portfolio/blob/main/Python/Mini_Project_Superstore_Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **📊 Mini Project: Superstore Sales Analysis**
🎯**Objective**

Analyze a retail company's sales data to answer business questions and provide insights that could help improve sales and profitability.

In [1]:
from google.colab import files

uploaded = files.upload()

Saving Superstore.xls to Superstore.xls

# Load the Data

In [62]:
import pandas as pd
import numpy as np

# excel sheet laoded
df = pd.read_excel("Superstore.xls",sheet_name="Orders")

# disply first 5 records
print("First Five Records : \n\n",df.head(5))

#display last 5 records
print("First Five Records : \n\n",df.tail(5))

First Five Records :

    Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
1       2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
2       3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045
3       4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335
4       5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]
First Five Records :

       Row ID        Order ID Order Date  Ship Date       Ship Mode  \
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class

     Customer ID     Customer Name   Segment        Country         City  ...  \
9989    TB-21400  Tom Boeckenhauer  Consumer  United States        Miami  ...
9990    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa  ...
9991    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa  ...
9992    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa  ...
9993    CC-12220      Chris Cortes  Consumer  United States  Westminster  ...

     Postal Code  Region       Product ID         Category Sub-Category  \
9989       33180   South  FUR-FU-10001889        Furniture  Furnishings
9990       92627    West  FUR-FU-10000747        Furniture  Furnishings
9991       92627    West  TEC-PH-10003645       Technology       Phones
9992       92627    West  OFF-PA-10004041  Office Supplies        Paper
9993       92683    West  OFF-AP-10002684  Office Supplies   Appliances

                                           Product Name    Sales  Quantity  \
9989                             Ultra Door Pull Handle   25.248         3
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.960         2
9991                              Aastra 57i VoIP phone  258.576         2
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.600         4
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.160         2

      Discount   Profit
9989       0.2   4.1028
9990       0.0  15.6332
9991       0.2  19.3932
9992       0.0  13.3200
9993       0.0  72.9480

[5 rows x 21 columns]

# Understand the Dataset

In [16]:
print("Dimensions of dataframe")
df.shape

Dimensions of dataframe

(9994, 21)

In [17]:
print("No of Rows",df.shape[0])

No of Rows 9994

In [18]:
print("No of column",df.shape[1])

No of column 21

In [19]:
print("Name of Columns : \n")
df.columns

Name of Columns :

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [29]:
print("Datatype \n",df.dtypes)

Datatype
 Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [22]:
print("Summary Statistics :")
df.describe()

Summary Statistics :

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

In [26]:
print("Missing values ")
df.isnull().sum()

Missing values

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [28]:
print("Duplicate Data :")
print(df.duplicated().sum())

Duplicate Data :
0

# Data Cleaning

In [37]:
# Data Cleaning

df['Order Date'] = pd.to_datetime(df['Order Date'])
print(df['Order Date'].head())

0      2016-11-08
1      2016-11-08
2      2016-06-12
3      2015-10-11
4      2015-10-11
          ...
9989   2014-01-21
9990   2017-02-26
9991   2017-02-26
9992   2017-02-26
9993   2017-05-04
Name: Order Date, Length: 9994, dtype: datetime64[ns]
0   2016-11-08
1   2016-11-08
2   2016-06-12
3   2015-10-11
4   2015-10-11
Name: Order Date, dtype: datetime64[ns]

In [39]:

df['Ship Date'] = pd.to_datetime(df['Ship Date'])
print(df['Ship Date'].head())

0   2016-11-11
1   2016-11-11
2   2016-06-16
3   2015-10-18
4   2015-10-18
Name: Ship Date, dtype: datetime64[ns]

In [75]:
print(df.columns)
#renaming coloumns
df.rename(columns={'Order Date': 'order_date'}, inplace=True)
print(df.columns)
# rename again to its original
df.rename(columns={'order_date': 'Order Date'}, inplace=True)
print(df.columns)

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')
Index(['Row ID', 'Order ID', 'order_date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')
Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

# Basic Business Analysis

In [76]:
print("Total Sales",df['Sales'].sum())
print("Average Sales",df['Sales'].mean())
print("Maximum Sales",df['Sales'].max())
print("Minimum Sales",df['Sales'].min())

Total Sales 2297200.8603000003
Average Sales 229.85800083049833
Maximum Sales 22638.48
Minimum Sales 0.44399999999999995

In [78]:
print("Total Profit",df['Profit'].sum())
print("Average Profit",df['Profit'].mean())

Total Profit 286397.0216999999
Average Profit 28.656896307784663

In [83]:
print("Total number of orders",df["Order ID"].nunique())

Total number of orders 5009

# Category Analysis

In [134]:
print("Sales by Category:",df.groupby("Category")["Sales"].sum().sort_values(ascending=False))

print("\n\nProfit by Category : ",df.groupby("Category")["Profit"].sum().sort_values(ascending=False))
print("\n\nQuantity sold by category:",df.groupby("Category")["Quantity"].sum().sort_values(ascending=False))

Sales by Category: Category
Technology         836154.0330
Furniture          741999.7953
Office Supplies    719047.0320
Name: Sales, dtype: float64


Profit by Category :  Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: Profit, dtype: float64


Quantity sold by category: Category
Office Supplies    22906
Furniture           8028
Technology          6939
Name: Quantity, dtype: int64

# Sub-Category Analysis

In [146]:
print("Top 10 sub-categories by sales")

df.groupby("Sub-Category")["Sales"].sum().sort_values(ascending=False).head(10)

Top 10 sub-categories by sales

Sub-Category
Phones         330007.0540
Chairs         328449.1030
Storage        223843.6080
Tables         206965.5320
Binders        203412.7330
Machines       189238.6310
Accessories    167380.3180
Copiers        149528.0300
Bookcases      114879.9963
Appliances     107532.1610
Name: Sales, dtype: float64

In [150]:
print("Bottom 10 sub-categories by profit")

df.groupby("Sub-Category")["Profit"].sum().sort_values(ascending=True).head(10)

Bottom 10 sub-categories by profit

Sub-Category
Tables        -17725.4811
Bookcases      -3472.5560
Supplies       -1189.0995
Fasteners        949.5182
Machines        3384.7569
Labels          5546.2540
Art             6527.7870
Envelopes       6964.1767
Furnishings    13059.1436
Appliances     18138.0054
Name: Profit, dtype: float64

# Regional Analysis

In [154]:
print("Sales by Region :",df.groupby("Region")["Sales"].sum().sort_values(ascending=False))
print("\n\nProfit by Region :",df.groupby("Region")["Profit"].sum().sort_values(ascending=False))

Sales by Region : Region
West       725457.8245
East       678781.2400
Central    501239.8908
South      391721.9050
Name: Sales, dtype: float64


Profit by Region : Region
West       108418.4489
East        91522.7800
South       46749.4303
Central     39706.3625
Name: Profit, dtype: float64

# State Analysis

In [155]:
print("Top 10 states by sales :\n")
df.groupby("State")["Sales"].sum().sort_values(ascending=False).head(10)

Top 10 states by sales :

State
California      457687.6315
New York        310876.2710
Texas           170188.0458
Washington      138641.2700
Pennsylvania    116511.9140
Florida          89473.7080
Illinois         80166.1010
Ohio             78258.1360
Michigan         76269.6140
Virginia         70636.7200
Name: Sales, dtype: float64

In [157]:
print("Top 10 states by profit : ")
df.groupby("State")["Profit"].sum().sort_values(ascending=False).head(10)

Top 10 states by profit :

State
California    76381.3871
New York      74038.5486
Washington    33402.6517
Michigan      24463.1876
Virginia      18597.9504
Indiana       18382.9363
Georgia       16250.0433
Kentucky      11199.6966
Minnesota     10823.1874
Delaware       9977.3748
Name: Profit, dtype: float64

# Customer Analysis

In [159]:
print("Top 10 customers by sales")
df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(10)

Top 10 customers by sales

Customer Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64

In [160]:
print("Top 10 customers by profit")
df.groupby("Customer Name")["Profit"].sum().sort_values(ascending=False).head(10)

Top 10 customers by profit

Customer Name
Tamara Chand            8981.3239
Raymond Buch            6976.0959
Sanjit Chand            5757.4119
Hunter Lopez            5622.4292
Adrian Barton           5444.8055
Tom Ashbrook            4703.7883
Christopher Martinez    3899.8904
Keith Dawkins           3038.6254
Andy Reiter             2884.6208
Daniel Raglin           2869.0760
Name: Profit, dtype: float64

# Product Analysis

In [128]:
print("Top 10 products by sales\n")
df.groupby("Product Name")["Sales"].sum().sort_values(ascending =False).head(10)

Top 10 products by sales

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

In [127]:
print("Top 10 profitable product\n")
df.groupby("Product Name")["Profit"].sum().sort_values(ascending=False).head(10)

Top 10 profitable product

Product Name
Canon imageCLASS 2200 Advanced Copier                                          25199.9280
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind     7753.0390
Hewlett Packard LaserJet 3310 Copier                                            6983.8836
Canon PC1060 Personal Laser Copier                                              4570.9347
HP Designjet T520 Inkjet Large Format Printer - 24" Color                       4094.9766
Ativa V4110MDD Micro-Cut Shredder                                               3772.9461
3D Systems Cube Printer, 2nd Generation, Magenta                                3717.9714
Plantronics Savi W720 Multi-Device Wireless Headset System                      3696.2820
Ibico EPK-21 Electric Binding System                                            3345.2823
Zebra ZM400 Thermal Label Printer                                               3343.5360
Name: Profit, dtype: float64

# Time Analysis

In [166]:
df["Year"]=df["Order Date"].dt.year
df["Month"]=df["Order Date"].dt.month
df["Day"]=df["Order Date"].dt.day
print(df[["Order Date", "Year", "Month", "Day"]].head())

#Monthly sales



#Monthly profit
#Which month had the highest sales?
#Which month had the highest profit?

  Order Date  Year  Month  Day
0 2016-11-08  2016     11    8
1 2016-11-08  2016     11    8
2 2016-06-12  2016      6   12
3 2015-10-11  2015     10   11
4 2015-10-11  2015     10   11

Month
11    352461.071
Name: Sales, dtype: float64

In [170]:
print("Monthly sales")
df.groupby("Month")["Sales"].sum().sort_values(ascending=False)

Monthly sales

Month
11    352461.0710
12    325293.5035
9     307649.9457
3     205005.4888
10    200322.9847
8     159044.0630
5     155028.8117
6     152718.6793
7     147238.0970
4     137762.1286
1      94924.8356
2      59751.2514
Name: Sales, dtype: float64

In [171]:
print("Monthly profit")
df.groupby("Month")["Profit"].sum().sort_values(ascending=False)

Monthly profit

Month
12    43369.1919
9     36857.4753
11    35468.4265
10    31784.0413
3     28594.6872
5     22411.3078
8     21776.9384
6     21285.7954
7     13832.6648
4     11587.4363
2     10294.6107
1      9134.4461
Name: Profit, dtype: float64

In [174]:
print("Which month had the highest sales?")

df.groupby("Month")["Sales"].sum().sort_values(ascending=False).head(1)

Which month had the highest sales?

Month
11    352461.071
Name: Sales, dtype: float64

In [175]:
print(" Which month had the highest profit?")
df.groupby("Month")["Profit"].sum().sort_values(ascending=False).head(1)

 Which month had the highest profit?

Month
12    43369.1919
Name: Profit, dtype: float64

# Discount Analysis



1.Average discount
2.Which category gives the highest discount?
3. Does higher discount always mean higher profit?

In [182]:
print("Average Discount")
df["Discount"].mean()

Average Discount

np.float64(0.15620272163297977)

In [185]:
print("Which category gives the highest discount")
df.groupby("Category")["Discount"].max().sort_values(ascending=False)

Which category gives the highest discount

Category
Office Supplies    0.8
Furniture          0.7
Technology         0.7
Name: Discount, dtype: float64

In [188]:
print("Does higher discount always mean higher profit")
df.groupby("Discount")["Profit"].mean().sort_index()

Does higher discount always mean higher profit

Discount
0.00     66.900292
0.10     96.055074
0.15     27.288298
0.20     24.702572
0.30    -45.679636
0.32    -88.560656
0.40   -111.927429
0.45   -226.646464
0.50   -310.703456
0.60    -43.077212
0.70    -95.874060
0.80   -101.796797
Name: Profit, dtype: float64

# Filtering Practice

Find:

Orders with Sales > 1000

Orders where Region == West

Furniture orders only

Technology orders with Profit > 500

In [190]:
print("Orders with Sales > 1000 : ")
df[df["Sales"]>1000]

Orders with Sales > 1000 :

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Day
10,11,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184,9,0.2,85.3092,2014,6,9
24,25,CA-2015-106320,2015-09-25,2015-09-30,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630,3,0.0,240.2649,2015,9,25
27,28,US-2015-150630,2015-09-17,2015-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,7,0.5,-1665.0522,2015,9,17
35,36,CA-2016-117590,2016-12-08,2016-12-10,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,Technology,Phones,GE 30524EE4,1097.544,7,0.2,123.4737,2016,12,8
54,55,CA-2016-105816,2016-12-11,2016-12-17,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,...,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.950,5,0.0,298.6855,2016,12,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9866,9867,US-2015-116981,2015-03-26,2015-03-28,Second Class,SM-20950,Suzanne McNair,Corporate,United States,New York City,...,Office Supplies,Storage,"Dual Level, Single-Width Filing Carts",1085.420,7,0.0,282.2092,2015,3,26
9925,9926,CA-2015-159534,2015-03-20,2015-03-23,First Class,DH-13075,Dave Hallsten,Corporate,United States,New York City,...,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,1087.936,8,0.2,353.5792,2015,3,20
9929,9930,CA-2016-129630,2016-09-04,2016-09-04,Same Day,IM-15055,Ionia McGrath,Consumer,United States,San Francisco,...,Technology,Copiers,Canon PC1060 Personal Laser Copier,2799.960,5,0.2,944.9865,2016,9,4
9947,9948,CA-2017-121559,2017-06-01,2017-06-03,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,Furniture,Chairs,Hon 4070 Series Pagoda Round Back Stacking Chairs,1925.880,6,0.0,539.2464,2017,6,1
9948,9949,CA-2017-121559,2017-06-01,2017-06-03,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,Office Supplies,Appliances,Honeywell Enviracaire Portable HEPA Air Cleane...,2405.200,8,0.0,793.7160,2017,6,1

In [191]:
print("Orders where Region == West")
df[df["Region"]=="West"]

Orders where Region == West

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Day
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714,2016,6,12
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694,2014,6,9
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656,2014,6,9
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6,0.2,90.7152,2014,6,9
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825,2014,6,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9986,9987,CA-2016-125794,2016-09-29,2016-10-03,Standard Class,ML-17410,Maris LaWare,Consumer,United States,Los Angeles,...,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.240,1,0.0,15.2208,2016,9,29
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332,2017,2,26
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932,2017,2,26
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200,2017,2,26
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480,2017,5,4

In [192]:
print("Furniture orders only")
df[df["Category"]=="Furniture"]

Furniture orders only

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Day
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,8
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,8
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,11
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694,2014,6,9
10,11,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092,2014,6,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9962,9963,CA-2015-168088,2015-03-19,2015-03-22,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,Furniture,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,4,0.32,-67.6704,2015,3,19
9964,9965,CA-2016-146374,2016-12-05,2016-12-10,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,...,Furniture,Furnishings,Electrix 20W Halogen Replacement Bulb for Zoom...,13.4000,1,0.00,6.4320,2016,12,5
9980,9981,US-2015-151435,2015-09-06,2015-09-09,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,...,Furniture,Tables,KI Adjustable-Height Table,85.9800,1,0.00,22.3548,2015,9,6
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,2014,1,21
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,2017,2,26

In [196]:
print("Technology orders with Profit > 500")
df[(df["Category"]=="Technology") & (df["Profit"] > 500)]

Technology orders with Profit > 500

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Day
251,252,CA-2016-145625,2016-09-11,2016-09-17,Standard Class,KC-16540,Kelly Collister,Consumer,United States,San Diego,...,Technology,Accessories,Logitech P710e Mobile Speakerphone,3347.37,13,0.0,636.0003,2016,9,11
318,319,CA-2014-164973,2014-11-04,2014-11-09,Standard Class,NM-18445,Nathan Mautz,Home Office,United States,New York City,...,Technology,Machines,Canon imageCLASS MF7460 Monochrome Digital Las...,3991.98,2,0.0,1995.9900,2014,11,4
392,393,US-2014-135972,2014-09-21,2014-09-23,Second Class,JG-15115,Jack Garza,Consumer,United States,Des Moines,...,Technology,Copiers,Canon PC1080F Personal Copier,1799.97,3,0.0,701.9883,2014,9,21
515,516,CA-2017-127432,2017-01-22,2017-01-27,Standard Class,AD-10180,Alan Dominguez,Home Office,United States,Great Falls,...,Technology,Copiers,Canon Image Class D660 Copier,2999.95,5,0.0,1379.9770,2017,1,22
814,815,CA-2017-143686,2017-05-14,2017-05-14,Same Day,PJ-19015,Pauline Johnson,Consumer,United States,Santa Ana,...,Technology,Accessories,Razer Tiamat Over Ear 7.1 Surround Sound PC Ga...,1399.93,7,0.0,601.9699,2017,5,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8990,8991,US-2015-128587,2015-12-24,2015-12-30,Standard Class,HM-14860,Harry Marie,Corporate,United States,Springfield,...,Technology,Copiers,Canon PC1060 Personal Laser Copier,4899.93,7,0.0,2302.9671,2015,12,24
9165,9166,CA-2016-100300,2016-06-24,2016-06-26,Second Class,MJ-17740,Max Jones,Consumer,United States,San Diego,...,Technology,Machines,Okidata MB760 Printer,4476.80,4,0.2,503.6400,2016,6,24
9398,9399,CA-2014-125997,2014-09-20,2014-09-23,First Class,MW-18220,Mitch Webber,Consumer,United States,New York City,...,Technology,Phones,Panasonic KX-TG9541B DECT 6.0 Digital 2-Line E...,1349.91,9,0.0,661.4559,2014,9,20
9513,9514,CA-2016-125220,2016-10-14,2016-10-19,Standard Class,BE-11410,Bobby Elias,Consumer,United States,Appleton,...,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,1649.75,5,0.0,544.4175,2016,10,14
9929,9930,CA-2016-129630,2016-09-04,2016-09-04,Same Day,IM-15055,Ionia McGrath,Consumer,United States,San Francisco,...,Technology,Copiers,Canon PC1060 Personal Laser Copier,2799.96,5,0.2,944.9865,2016,9,4

# Sorting

Sort:

Highest sales first

Highest profit first

Lowest discount first

In [198]:
print("Highest sales first")
df.sort_values("Sales",ascending=False)

Highest sales first

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Day
2697,2698,CA-2014-145317,2014-03-18,2014-03-23,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784,2014,3,18
6826,6827,CA-2016-118689,2016-10-02,2016-10-09,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760,2016,10,2
8153,8154,CA-2017-140151,2017-03-23,2017-03-25,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808,2017,3,23
2623,2624,CA-2017-127180,2017-10-22,2017-10-24,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888,2017,10,22
4190,4191,CA-2017-166709,2017-11-17,2017-11-22,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856,2017,11,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,2107,US-2014-152723,2014-09-26,2014-09-26,Same Day,HG-14965,Henry Goldwyn,Corporate,United States,Mesquite,...,Office Supplies,Binders,Acco 3-Hole Punch,0.876,1,0.8,-1.4016,2014,9,26
4711,4712,CA-2014-112403,2014-03-31,2014-03-31,Same Day,JO-15280,Jas O'Carroll,Consumer,United States,Philadelphia,...,Office Supplies,Binders,Avery Round Ring Poly Binders,0.852,1,0.7,-0.5964,2014,3,31
8658,8659,CA-2016-168361,2016-06-21,2016-06-25,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Chicago,...,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,0.836,1,0.8,-1.3376,2016,6,21
9292,9293,CA-2017-124114,2017-03-02,2017-03-02,Same Day,RS-19765,Roland Schwarz,Corporate,United States,Waco,...,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,0.556,1,0.8,-0.9452,2017,3,2
4101,4102,US-2017-102288,2017-06-19,2017-06-23,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,...,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,2017,6,19

In [199]:
print("Highest profit first")
df.sort_values("Profit",ascending=False)

Highest profit first

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Day
6826,6827,CA-2016-118689,2016-10-02,2016-10-09,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760,2016,10,2
8153,8154,CA-2017-140151,2017-03-23,2017-03-25,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808,2017,3,23
4190,4191,CA-2017-166709,2017-11-17,2017-11-22,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856,2017,11,17
9039,9040,CA-2016-117121,2016-12-17,2016-12-21,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,...,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,13,0.0,4946.3700,2016,12,17
4098,4099,CA-2014-116904,2014-09-23,2014-09-28,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,...,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950,5,0.0,4630.4755,2014,9,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4991,4992,US-2017-122714,2017-12-07,2017-12-13,Standard Class,HG-14965,Henry Goldwyn,Corporate,United States,Chicago,...,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,1889.990,5,0.8,-2929.4845,2017,12,7
3011,3012,CA-2017-134845,2017-04-17,2017-04-23,Standard Class,SR-20425,Sharelle Roach,Home Office,United States,Louisville,...,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,2549.985,5,0.7,-3399.9800,2017,4,17
9774,9775,CA-2014-169019,2014-07-26,2014-07-30,Standard Class,LF-17185,Luke Foster,Consumer,United States,San Antonio,...,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,2177.584,8,0.8,-3701.8928,2014,7,26
683,684,US-2017-168116,2017-11-04,2017-11-04,Same Day,GT-14635,Grant Thornton,Corporate,United States,Burlington,...,Technology,Machines,Cubify CubeX 3D Printer Triple Head Print,7999.980,4,0.5,-3839.9904,2017,11,4
7772,7773,CA-2016-108196,2016-11-25,2016-12-02,Standard Class,CS-12505,Cindy Stewart,Consumer,United States,Lancaster,...,Technology,Machines,Cubify CubeX 3D Printer Double Head Print,4499.985,5,0.7,-6599.9780,2016,11,25

In [200]:
print("Lowest discount first")
df.sort_values("Discount",ascending=True)

Lowest discount first

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Day
3268,3269,CA-2014-143840,2014-05-22,2014-05-29,Standard Class,EH-14185,Evan Henry,Consumer,United States,Decatur,...,Technology,Phones,Plantronics Encore H101 Dual Earpieces Headset,44.950,1,0.0,12.5860,2014,5,22
3290,3291,CA-2015-157770,2015-12-13,2015-12-15,First Class,RD-19585,Rob Dowd,Consumer,United States,Temecula,...,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.240,1,0.0,15.2208,2015,12,13
3291,3292,CA-2016-167290,2016-10-30,2016-11-04,Standard Class,JF-15295,Jason Fortune-,Consumer,United States,Sterling Heights,...,Office Supplies,Art,Newell 312,11.680,2,0.0,3.5040,2016,10,30
3292,3293,CA-2014-106264,2014-12-26,2014-12-30,Standard Class,CK-12595,Clytie Kelty,Consumer,United States,San Diego,...,Office Supplies,Supplies,Acme Rosewood Handle Letter Opener,11.910,3,0.0,0.1191,2014,12,26
3293,3294,CA-2014-106264,2014-12-26,2014-12-30,Standard Class,CK-12595,Clytie Kelty,Consumer,United States,San Diego,...,Furniture,Furnishings,"Eldon Regeneration Recycled Desk Accessories, ...",3.480,2,0.0,1.1136,2014,12,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4957,4958,CA-2015-127607,2015-03-20,2015-03-26,Standard Class,JK-15730,Joe Kamberova,Consumer,United States,Carrollton,...,Office Supplies,Binders,GBC Standard Plastic Binding Systems' Combs,2.512,2,0.8,-4.3960,2015,3,20
4820,4821,CA-2015-140025,2015-04-07,2015-04-11,Standard Class,PF-19120,Peter Fuller,Consumer,United States,San Antonio,...,Office Supplies,Appliances,Hoover Upright Vacuum With Dirt Cup,463.248,8,0.8,-1181.2824,2015,4,7
5048,5049,US-2014-104759,2014-03-31,2014-04-04,Standard Class,DD-13570,Dorothy Dickinson,Consumer,United States,Chicago,...,Office Supplies,Binders,Fellowes Black Plastic Comb Bindings,8.134,7,0.8,-13.8278,2014,3,31
14,15,US-2015-118983,2015-11-22,2015-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.810,5,0.8,-123.8580,2015,11,22
5093,5094,US-2014-140452,2014-12-06,2014-12-10,Standard Class,BK-11260,Berenike Kampe,Consumer,United States,Chicago,...,Office Supplies,Appliances,Bionaire 99.97% HEPA Air Cleaner,14.016,4,0.8,-31.5360,2014,12,6

# Apply and Map

Practice:

Create a new column such as:

Profit Status ("Profit" / "Loss")

Sales Category ("Low", "Medium", "High")

Use map() to convert Region names to short codes (for example, West → W, East → E).

In [207]:
print("Profit Status (Profit / Loss)")
df["Profit_Status"]=df["Profit"].apply(lambda x:"Profit" if x>0 else "Loss")
#df["Profit_Status"]=df["Profit"].apply(lambda x:"Profit" if x>0 else "Loss")
df[["Profit","Profit_Status"]]

Profit Status (Profit / Loss)

        Profit Profit_Status
0      41.9136        Profit
1     219.5820        Profit
2       6.8714        Profit
3    -383.0310          Loss
4       2.5164        Profit
...        ...           ...
9989    4.1028        Profit
9990   15.6332        Profit
9991   19.3932        Profit
9992   13.3200        Profit
9993   72.9480        Profit

[9994 rows x 2 columns]

In [208]:
print("Sales Category (Low, Medium, High)")
df["Sales_Category"]=df["Sales"].apply(lambda x:"Low" if x<1000 else ("Medium" if x<5000 else "High"))
df[["Sales","Sales_Category"]]

Sales Category (Low, Medium, High)

         Sales Sales_Category
0     261.9600            Low
1     731.9400            Low
2      14.6200            Low
3     957.5775            Low
4      22.3680            Low
...        ...            ...
9989   25.2480            Low
9990   91.9600            Low
9991  258.5760            Low
9992   29.6000            Low
9993  243.1600            Low

[9994 rows x 2 columns]

In [210]:
print("Use map() to convert Region names to short codes (for example, West → W, East → E).")
df["Region_Code"]=df["Region"].map({"West":"W","East":"E","Central":"C","South":"S"})
df[["Region","Region_Code"]]

Use map() to convert Region names to short codes (for example, West → W, East → E).

     Region Region_Code
0     South           S
1     South           S
2      West           W
3     South           S
4     South           S
...     ...         ...
9989  South           S
9990   West           W
9991   West           W
9992   West           W
9993   West           W

[9994 rows x 2 columns]

In [212]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Year,Month,Day,Profit_Status,Sales_Category,Region_Code
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.96,2,0.0,41.9136,2016,11,8,Profit,Low,S
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.94,3,0.0,219.5820,2016,11,8,Profit,Low,S
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.62,2,0.0,6.8714,2016,6,12,Profit,Low,W

# Export

Save the cleaned dataset:

Excel (to_excel())
CSV (to_csv())

In [213]:
df.to_excel("Cleaned_Superstore_Data.xlsx", index=False)

In [214]:
import os

os.listdir()

['.config', 'Superstore.xls', 'Cleaned_Superstore_Data.xlsx', 'sample_data']